version: 2

models:
  - name: dim_customers
    description: >
      Customer dimension table enriched with lifetime order metrics.
      Joins stg_customers with aggregated order data.
    columns:
      - name: customer_id
        description: Unique identifier for each customer.
        tests:
          - not_null
          - unique
      - name: first_name
        description: Customer first name.
        tests:
          - not_null
      - name: last_name
        description: Customer last name.
        tests:
          - not_null
      - name: full_name
        description: Concatenation of first_name and last_name.
        tests:
          - not_null
      - name: email
        description: Customer email address.
        tests:
          - not_null
          - unique
      - name: phone
        description: Customer phone number.
      - name: country
        description: Customer country.
      - name: city
        description: Customer city.
      - name: first_order_date
        description: Date of the customer's first order.
      - name: most_recent_order_date
        description: Date of the customer's most recent order.
      - name: number_of_orders
        description: Total number of orders placed by the customer.
        tests:
          - not_null
      - name: lifetime_value
        description: Total spend (sum of total_price) across all orders.
        tests:
          - not_null
      - name: created_at
        description: Timestamp when the customer record was created.
      - name: updated_at
        description: Timestamp when the record was last updated.

  - name: dim_products
    description: >
      Product dimension table enriched with sales metrics.
      Joins stg_products with aggregated non-cancelled order data.
    columns:
      - name: product_id
        description: Unique identifier for each product.
        tests:
          - not_null
          - unique
      - name: product_name
        description: Name of the product.
        tests:
          - not_null
      - name: category
        description: Product category.
        tests:
          - not_null
      - name: subcategory
        description: Product subcategory.
      - name: unit_price
        description: Current unit price of the product in dollars.
        tests:
          - not_null
      - name: is_active
        description: Whether the product is currently active.
        tests:
          - not_null
      - name: total_units_sold
        description: Total units sold across all non-cancelled orders.
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue generated by the product.
        tests:
          - not_null
      - name: created_at
        description: Timestamp when the product record was created.
      - name: updated_at
        description: Timestamp when the record was last updated.

  - name: fct_orders
    description: >
      Central fact table for order-level analysis.
      Joins stg_orders with customer and product dimension data.
    columns:
      - name: order_id
        description: Unique identifier for each order.
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Foreign key to dim_customers.
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: customer_name
        description: Customer full name.
      - name: customer_email
        description: Customer email address.
      - name: customer_country
        description: Customer country.
      - name: product_id
        description: Foreign key to dim_products.
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: product_name
        description: Product name.
      - name: product_category
        description: Product category.
      - name: product_subcategory
        description: Product subcategory.
      - name: order_date
        description: Date the order was placed.
        tests:
          - not_null
      - name: quantity
        description: Number of units ordered.
        tests:
          - not_null
          - positive_value
      - name: unit_price
        description: Unit price in dollars at time of order.
        tests:
          - not_null
      - name: total_price
        description: Total order value in dollars.
        tests:
          - not_null
      - name: status
        description: Order status.
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'processing', 'shipped', 'delivered', 'cancelled']
      - name: created_at
        description: Timestamp when the record was created.
      - name: updated_at
        description: Timestamp when the record was last updated.

  - name: mart_customer_orders
    description: >
      Customer-level aggregated order analytics mart.
      Summarises total orders, revenue, and average order value per customer.
    columns:
      - name: customer_id
        description: Unique identifier for each customer.
        tests:
          - not_null
          - unique
      - name: customer_name
        description: Customer full name.
      - name: customer_email
        description: Customer email address.
      - name: customer_country
        description: Customer country.
      - name: total_orders
        description: Total number of orders placed.
        tests:
          - not_null
      - name: delivered_orders
        description: Number of orders with status = delivered.
        tests:
          - not_null
      - name: cancelled_orders
        description: Number of orders with status = cancelled.
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue from non-cancelled orders.
      - name: first_order_date
        description: Date of the customer's first order.
      - name: last_order_date
        description: Date of the customer's most recent order.
      - name: avg_order_value
        description: Average order value for non-cancelled orders.
