version: 2

sources:
  - name: bronze
    description: >
      Raw data loaded from AWS S3 into Snowflake's bronze schema.
      These tables are populated via Snowflake external stages or COPY INTO commands
      and represent the landing zone for all ingested data.
    database: "CAPSTONE_DG"
    schema: bronze
    tables:
      - name: raw_orders
        columns:
          - name: order_id
            tests:
              - not_null
              - unique
          - name: customer_id
            tests:
              - not_null
          - name: order_status
            tests:
              - not_null
          - name: order_purchase_timestamp
            tests:
              - not_null

      - name: raw_order_items
        columns:
          - name: order_id
            tests:
              - not_null
          - name: order_item_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: seller_id
            tests:
              - not_null

      - name: raw_order_payments
        columns:
          - name: order_id
            tests:
              - not_null
          - name: payment_sequential
            tests:
              - not_null
          - name: payment_type
            tests:
              - not_null

      - name: raw_order_reviews
        columns:
          - name: review_id
            tests:
              - not_null
          - name: order_id
            tests:
              - not_null
          - name: review_score
            tests:
              - not_null

      - name: raw_customers
        columns:
          - name: customer_id
            tests:
              - not_null
              - unique
          - name: customer_unique_id
            tests:
              - not_null

      - name: raw_geolocation
        columns:
          - name: geolocation_zip_code_prefix
            tests:
              - not_null
          - name: geolocation_city
            tests:
              - not_null
          - name: geolocation_state
            tests:
              - not_null

      - name: raw_products
        columns:
          - name: product_id
            tests:
              - not_null
              - unique
          - name: product_category_name

      - name: raw_product_category_name_translation
        columns:
          - name: product_category_name
            tests:
              - not_null
              - unique

      - name: raw_sellers
        columns:
          - name: seller_id
            tests:
              - not_null
              - unique
          - name: seller_zip_code_prefix
            tests:
              - not_null
          - name: seller_city
            tests:
              - not_null
          - name: seller_state
            tests:
              - not_null